create proc SP_DSGV 
AS 
BEGIN
	--SELECT MAGV AS MAGV FROM GIAOVIEN WHERE NOT EXISTS (SELECT MAGV FROM THAMGIADT WHERE THAMGIADT.MAGV=GIAOVIEN.MAGV)

	--SELECT MAGV,COUNT(DISTINCT MADT) AS SODTTG
	--FROM THAMGIADT 
	--GROUP BY MAGV 
	--HAVING COUNT(DISTINCT MADT)>=ALL 
	--			(SELECT COUNT(DISTINCT MADT)
	--				FROM THAMGIADT
	--				GROUP BY MAGV) 

	--SELECT GVCNDT,COUNT(DISTINCT MADT) AS SODTCN
	--FROM DETAI
	--GROUP BY GVCNDT
	--HAVING COUNT(DISTINCT MADT)>=ALL 
	--			(SELECT COUNT(DISTINCT MADT)
	--				FROM DETAI
	--				GROUP BY GVCNDT) 
	SELECT GV.MAGV AS MAGV, COUNT(DISTINCT TG.MADT) AS SODT, COUNT(DISTINCT DT.GVCNDT) AS SODTCN
	FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
	WHERE GV.MAGV=TG.MAGV AND DT.MADT=TG.MADT
	GROUP BY GV.MAGV
END
GO
EXECUTE SP_DSGV


--2
CREATE PROC DSGV_100 
AS
BEGIN
	SELECT *
	FROM GIAOVIEN GV
	WHERE GV.MAGV IN
		(
			SELECT TG.MAGV
			FROM THAMGIADT TG JOIN DETAI DT
			ON TG.MADT=DT.MADT
			AND DT.KINHPHI>100
			GROUP BY TG.MAGV
			HAVING COUNT(TG.MADT)>=ALL
					(
						SELECT COUNT(TG.MADT)
						FROM THAMGIADT TG JOIN DETAI DT
						ON TG.MADT=DT.MADT
						AND DT.KINHPHI>100
						GROUP BY TG.MAGV
					)
		)
END
GO
EXECUTE DSGV_100

--3
CREATE PROC DSDTTG_MAGV
@MAGV VARCHAR(5)
AS
BEGIN
	SELECT DISTINCT DT.TENDT
	FROM DETAI DT JOIN THAMGIADT TG
	ON DT.MADT=TG.MADT
	AND TG.MAGV=@MAGV
END
GO 
EXECUTE DSDTTG_MAGV'003'

--4

CREATE PROC CAPNHATL_MAGV
@MAGV VARCHAR(5),
@LUONG INT
AS
BEGIN
	UPDATE GIAOVIEN
	SET LUONG=@LUONG
	WHERE MAGV=@MAGV
END
GO 
EXECUTE CAPNHATL_MAGV '003', 2200


--5

CREATE PROC XOA_MAGV
@MAGV VARCHAR(5)
AS
BEGIN
	DELETE FROM NGUOITHAN WHERE MAGV=@MAGV
END
GO
EXECUTE XOA_MAGV '002'

--6
CREATE PROC CNPHUCAP_MAGV_CV
@MAGV CHAR(5),
@MADT CHAR(5),
@STT INT,
@PHUCAP FLOAT
AS
BEGIN

	UPDATE THAMGIADT
	SET PHUCAP=@PHUCAP
	WHERE MADT=@MADT
	AND MAGV=@MAGV
	AND STT=@STT
END
GO
EXECUTE CNPHUCAP_MAGV_CV '002', '003', 2, 5



