--Vo Quang Dung 21bit
--2159001
--ma de gk33
DROP DATABASE QL_MIDTERM
CREATE DATABASE QL_MIDTERM
use QL_MIDTERM
CREATE TABLE GIAOVIEN 
(
	MAGV VARCHAR(5) ,
	TENGV NVARCHAR(30),
	DIACHI NVARCHAR(30),
	VAITRO NVARCHAR(20),
	CONSTRAINT FK_GIAOVIEN PRIMARY KEY(MAGV)
)	
CREATE TABLE THISINH
(
	SBD VARCHAR(4) ,
	DIEMTHI VARCHAR(4),
	HOTEN NVARCHAR(30),
	DIACHI NVARCHAR(20),
	NGAYSINH DATE,
	PHONGTHI VARCHAR(4) ,
	CONSTRAINT FK_THISINH PRIMARY KEY(SBD)
)
CREATE TABLE PHONGTHI
(
	IDPHONG VARCHAR(4) ,
	IDDIEMTHI VARCHAR(4),
	CANBO VARCHAR(5) ,
	SOBAN INT,
	THIETBI VARCHAR(20),
	CONSTRAINT FK_PHONGTHI PRIMARY KEY(IDPHONG,CANBO,IDDIEMTHI)
)
SET DATEFORMAT DMY
ALTER TABLE PHONGTHI
ADD
CONSTRAINT FK_PHONGTHI_GIAOVIEN FOREIGN KEY (CANBO) REFERENCES GIAOVIEN(MAGV)
go
ALTER TABLE THISINH
ADD CONSTRAINT FK_THISINH_PHONGTHI FOREIGN KEY(PHONGTHI,DIEMTHI) REFERENCES PHONGTHI(IDPHONG,IDDIEMTHI)

INSERT INTO  GIAOVIEN values ('GV001',N'Trần Thị Bé',N'31 Nguyễn Xí Q.Bình Thạnh','Cán bộ')
INSERT INTO  GIAOVIEN values ('GV002',N'Nguyễn Minh Tâm',N'2 Trần Hưng Đạo Q5','Giám sát')
INSERT INTO  GIAOVIEN values ('GV003',N'Trần Văn Lí',N'30 Hà Tồn Quyền Q5','Cán bộ')

INSERT INTO  PHONGTHI values ('P001','DD1','GV001',25,'Mic-Loa-Tivi')
INSERT INTO  PHONGTHI values ('P002','DD1','GV002',30,'Mic-Loa-Tivi')
INSERT INTO  PHONGTHI values ('P001','DD2','GV003',15,NULL)

INSERT INTO  THISINH values ('0231','DD1',N'Nguyễn Quan Tùng','TPHCM','20-11-2000','P001')
INSERT INTO  THISINH values ('0230','DD2',N'Lưu Phi Nam','Hải Phòng','12-2-2000','P001')
INSERT INTO  THISINH values ('0234','DD1',N'Lê Quang Bảo','Hà Nội','13-2-2000','P002')
INSERT INTO  THISINH values ('0233','DD2',N'Hà Ngọc Thúy','TPHCM','24-4-2000','P001')

SELECT P.IDPHONG,GV.TENGV
FROM PHONGTHI P JOIN GIAOVIEN GV ON P.CANBO=GV.MAGV JOIN THISINH TS ON P.IDPHONG=TS.PHONGTHI 
WHERE P.SOBAN>15 AND TS.DIACHI = N'Hải Phòng'
	



